### ISSUE TITLE
Feature request: Use Chromium or Mozilla motor instead of Edge WebView2

### ISSUE THREAD

**Issue by V1vidExplorer** [itzbluebxrry/Radon-Browser#7]
Edge WebView2 are for other contexts like web apps, not for browsers, see this information in https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features and explore other concepts of WebView in the left panel

**Comment by itzbluebxrry** [comment]
@V1vidExplorer Thanks for the suggestion, but it looks like I'm unable to fulfill this one. As far as I can see, WebView2 and legacy Edge WebView are the only Webview runtimes that can be implemented in UWP apps. As you mentioned Chromium (which is impossible to implement), WebView2 is also built based on Chromium engine—with further debloation and stripping off by MS while giving the same advantages you'd get on Chromium engine. As for Mozilla (I'd assume as Firefox here), I can't find any runtime that is compatible with UWP, not even for .NET though. I'm so sorry that I'd have to flag this as unplanned. 🙏🏻

**Comment by itzbluebxrry** [comment]
@V1vidExplorer Thanks for the suggestion, but it looks like I'm unable to fulfill this one. As far as I can see, WebView2 and legacy Edge WebView are the only Webview runtimes that can be implemented in UWP apps.

As you mentioned Chromium (which is impossible to implement), WebView2 is also built based on Chromium engine—with further debloation and stripping off by MS while giving the same advantages you'd get on Chromium engine.

As for Mozilla (I'd assume as Firefox here), I can't find any runtime that is compatible with UWP, not even for .NET though. I'm so sorry that I'd have to flag this as unplanned. 🙏🏻
